### ISSUE TITLE
provide geojson formatted version

### ISSUE THREAD

**Issue by ungoldman** [meandavejustice/Portland-park-data#1]
Would be cool to have this dataset available in [GeoJSON](http://geojson.org/geojson-spec.html) too.

@meandavejustice do you remember the source for this data?

**Comment by meandavejustice** [comment]
I don't remember off the top of my head, I'll have to do some digging. The intention was to replace this call to the civic apps api ==> http://www.civicapps.org/datasets/city-parks I'll let u know sometime this afternoon tho

**Comment by ungoldman** [comment]
I ended up producing the geojson dataset by using @Caged's https://github.com/caged/portland-atlas and converting from topojson to geojson. He's pulling down a zip of the shapefile directly from the civicapps FTP server (https://github.com/Caged/portland-atlas/blob/master/Makefile#L35).

If you want to try this method out watch out though, portland-atlas is super useful but you need to have Cairo installed for node-canvas, which requires some extra work outside of a regular npm install.
- https://www.npmjs.com/package/canvas#installation
- https://github.com/Automattic/node-canvas/issues/260#issuecomment-14935998

I might not be looking at the exact same dataset as you either -- I was looking specifically for polygons and multipolygons to do some testing and benchmarking for https://github.com/ngoldman/esri-extent. Here's a gist of what I ended up with: https://gist.github.com/ngoldman/e5c38eee056927975660

**Comment by ungoldman** [comment]
This makes me want to create a mirror of everything in ftp://ftp02.portlandoregon.gov/CivicApps/ with [dat](https://github.com/maxogden/dat) for versioning and [koop](https://github.com/Esri/koop) for downloading as different formats.

**Comment by ungoldman** [comment]
@ksmpdx relevant to our conversation from a couple of days ago ^

**Comment by meandavejustice** [comment]
@ngoldman This all looks great. I would be more than happy to assist in creating that mirror, I have yet to do anything with dat outside of some of the modules it uses. Would you be free sometime this weekend to meet up and hack/discuss this stuff?

**Comment by caged** [comment]
> I ended up producing the geojson dataset by using @Caged's https://github.com/caged/portland-atlas and converting from topojson to geojson.

You can skip the topojson step using something like `ogr2ogr -f GeoJSON parks.json shp/parks.shp`.

>  If you want to try this method out watch out though, portland-atlas is super useful but you need to have Cairo installed for node-canvas, which requires some extra work outside of a regular npm install.

You shouldn't need cairo unless you're trying to run `bin/rasterize`, which will create a PNG from the shapefile.

**Comment by ungoldman** [comment]
@Caged npm install on portland-atlas failed because of node-canvas -- does that mean I can just skip npm install altogether for the basic `make` stuff?

**Comment by ungoldman** [comment]
@meandavejustice doing the weekly civic study hall at bare bones this Sunday from 2:30 to 5:30 http://calagator.org/events/1250468086 -- that a good time for you?

**Comment by caged** [comment]
@ngoldman if you're just looking to download datasets and generate shapefiles, you can just use `make` and skip the `npm install` step since its purpose is to support topojson and rasterization.   You can also comment out the `canvas` dependency and run `npm install` and you'd get topojson support.

**Comment by ungoldman** [comment]
@Caged :+1: thanks for the protip dude

**Comment by meandavejustice** [comment]
@ngoldman I'll be there

**Comment by ksmpdx** [comment]
@ngoldman totally relevant. one goal of the civicapps refresh is to serve up geojson (as well as other flavors). but more importantly to publish more of the thousands of datasets the city is sitting on. note that the ftp may go away, not sure of the external dependencies. our current workflow for publishing data to that ftp server is ugly.

**Comment by caged** [comment]
(very sorry for hijacking this thread)

@ksmpdx @ngoldman is their any place where we can learn more about what's happening on the civicapps front and perhaps participate in the conversation? I've done a lot of work with the civicapps datasets (and website) and have a deep interest in seeing the next iteration be as amazing as possible. I'm also wondering what the process is going to be for decommissioning the current FTP server if it is indeed going away.

**Comment by ungoldman** [comment]
@Caged part of my conversation w/ @ksmpdx was getting you, @maxogden and @catnik involved in providing feedback to @ksmpdx's team and others about Portland's open data efforts, past and future.

(also sorry for hijacking :octopus:)

**Comment by ksmpdx** [comment]
@Caged @ngoldman yes, i should have mentioned that as well. goal is for you all to meet with our civicapps team before we get too far along in the refresh. we definitely want to hear from you, get some guidance, shop our ideas. shooting for early to mid april. i'll float some dates/times next week. final hijack!

**Comment by ungoldman** [comment]
Closing since much time has passed since this conversation. Hope y'all are doing well 👋
